name: cool_linter_plugin_loader
description: cool linter plugin loader
version: 2.3.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cool_linter:
    hosted:
      name: cool_linter
      url: https://unpub.bybit.com
    version: ^2.3.5